"use strict";
/* 内置示例库：每个示例可带 stdin 预填输入 */
const EXAMPLES = {
  py: [
    {
      title: '你好，世界',
      desc: 'print 输出 + f-string 格式化',
      stdin: '',
      code: [
        'name = "编程世界"',
        'print(f"你好，{name}！")',
        'print("这是我在手机上写的第一段 Python")',
      ].join('\n'),
    },
    {
      title: '九九乘法表',
      desc: 'for 循环嵌套 + print 不换行技巧',
      stdin: '',
      code: [
        'for i in range(1, 10):',
        '    for j in range(1, i + 1):',
        '        print(f"{i}x{j}={i*j}", end="\\t")',
        '    print()',
      ].join('\n'),
    },
    {
      title: '求平均分',
      desc: '读入一行输入，练习 input() 与列表统计',
      stdin: '88 92 75 63 100',
      code: [
        'print("请输入若干个成绩（空格分开）：")',
        'scores = [int(x) for x in input().split()]',
        'print(f"共 {len(scores)} 人")',
        'print(f"平均分：{sum(scores) / len(scores):.1f}")',
        'print(f"最高分：{max(scores)}，最低分：{min(scores)}")',
      ].join('\n'),
    },
    {
      title: '斐波那契数列',
      desc: 'while 循环 + 多变量同时赋值',
      stdin: '',
      code: [
        'a, b = 1, 1',
        'n = 1',
        'while a <= 100:',
        '    print(f"第{n}项：{a}")',
        '    a, b = b, a + b',
        '    n += 1',
      ].join('\n'),
    },
    {
      title: '数一数元音字母',
      desc: '字符串遍历、推导式与成员判断 in',
      stdin: 'Python makes coding fun on the phone',
      code: [
        'text = input("输入一行英文：")',
        'vowels = "aeiou"',
        'count = sum(1 for ch in text.lower() if ch in vowels)',
        'print(f"共有 {count} 个元音字母")',
      ].join('\n'),
    },
    {
      title: 'NumPy 数据分析',
      desc: '求平均/标准差一步到位（首次运行需加载库，请耐心等几秒）',
      stdin: '',
      code: [
        'import numpy as np',
        '',
        'a = np.array([88, 92, 75, 63, 100])',
        'print("成绩：", a)',
        'print("平均分：", round(a.mean(), 1))',
        'print("标准差：", round(a.std(), 2))',
        'print("最高/最低：", a.max(), a.min())',
      ].join('\n'),
    },
    {
      title: 'pandas 成绩表',
      desc: '表格数据分析（首次运行需加载库，请耐心等几秒）',
      stdin: '',
      code: [
        'import pandas as pd',
        '',
        'data = pd.DataFrame({',
        '    "姓名": ["小明", "小红", "小刚", "小美"],',
        '    "分数": [88, 92, 75, 63],',
        '})',
        'print(data)',
        'print("平均分：", data["分数"].mean())',
        'print("最高分：", data["分数"].max(), "→", data.loc[data["分数"].idxmax(), "姓名"])',
      ].join('\n'),
    },
  ],
  cpp: [
    {
      title: '你好，世界',
      desc: '程序基本骨架 + cout 输出',
      stdin: '',
      code: [
        '#include <iostream>',
        'using namespace std;',
        '',
        'int main() {',
        '    cout << "你好，C++！" << endl;',
        '    cout << "这是我在手机上写的第一个程序" << endl;',
        '    return 0;',
        '}',
      ].join('\n'),
    },
    {
      title: 'A+B 问题',
      desc: 'cin 读取输入（先在输入框里写两个数）',
      stdin: '3 5',
      code: [
        '#include <iostream>',
        'using namespace std;',
        '',
        'int main() {',
        '    int a, b;',
        '    cout << "请输入两个整数（空格隔开）：" << endl;',
        '    cin >> a >> b;',
        '    cout << a << " + " << b << " = " << a + b << endl;',
        '    return 0;',
        '}',
      ].join('\n'),
    },
    {
      title: '冒泡排序',
      desc: '数组 + 双重循环 + 交换',
      stdin: '',
      code: [
        '#include <iostream>',
        'using namespace std;',
        '',
        'int main() {',
        '    int a[6] = {5, 2, 8, 1, 9, 3};',
        '    for (int i = 0; i < 5; i++) {',
        '        for (int j = 0; j < 5 - i; j++) {',
        '            if (a[j] > a[j + 1]) {',
        '                int t = a[j];',
        '                a[j] = a[j + 1];',
        '                a[j + 1] = t;',
        '            }',
        '        }',
        '    }',
        '    cout << "排序结果：";',
        '    for (int i = 0; i < 6; i++) cout << a[i] << " ";',
        '    cout << endl;',
        '    return 0;',
        '}',
      ].join('\n'),
    },
    {
      title: '判断素数',
      desc: '自定义函数 + bool 返回值',
      stdin: '',
      code: [
        '#include <iostream>',
        'using namespace std;',
        '',
        'bool isPrime(int n) {',
        '    if (n < 2) return false;',
        '    for (int i = 2; i * i <= n; i++) {',
        '        if (n % i == 0) return false;',
        '    }',
        '    return true;',
        '}',
        '',
        'int main() {',
        '    cout << "2~50 之间的素数：" << endl;',
        '    for (int n = 2; n <= 50; n++) {',
        '        if (isPrime(n)) cout << n << " ";',
        '    }',
        '    cout << endl;',
        '    return 0;',
        '}',
      ].join('\n'),
    },
    {
      title: '成绩等级判定',
      desc: 'if / else if / else 分支',
      stdin: '86',
      code: [
        '#include <iostream>',
        'using namespace std;',
        '',
        'int main() {',
        '    int score;',
        '    cout << "请输入一个 0~100 的分数：" << endl;',
        '    cin >> score;',
        '    if (score >= 90) cout << "优秀 A" << endl;',
        '    else if (score >= 80) cout << "良好 B" << endl;',
        '    else if (score >= 60) cout << "及格 C" << endl;',
        '    else cout << "不及格，继续加油" << endl;',
        '    return 0;',
        '}',
      ].join('\n'),
    },
  ],
};
